### ISSUE TITLE
Searching in one buffer causes cursor to move in previous buffer

### ISSUE THREAD

**Issue by kgrimes2** [abo-abo/swiper-helm#16]
Observed behavior:

- In first  buffer. Switch to other buffer, and use "swiper" to search for keyword "import".
- Window pops up, showing occurrences of the word "import" in second buffer.
- Moving up and down in the options list moves the cursor in the first buffer.

Expected behavior:

- In first buffer. Switch to second buffer, and use "swiper" to search for keyword "import".
- Window pops up, showing occurrences of the word "import" in second buffer.
- Moving up and down in the options list moves the cursor in the second buffer.

I checked, and this behavior is unique to the Helm flavor of Swiper. It doesn't seem to happen in vanilla Swiper.

In this GIF, my cursor starts at the very bottom of the bottom buffer. I had just entered it from the top left buffer.

![ezgif-1-e23afb410d](https://user-images.githubusercontent.com/13686706/37183636-e085d2d8-22eb-11e8-84a3-a7cbf6f842fd.gif)

**Comment by abo-abo** [comment]
> Observed behavior:

OK, so you've got 3 different buffers A, B, C. Calling `swiper-helm` in A will search for words in A; the search results will pop up either in B or C - while inconvenient, this is expected.
Same thing if you search in B or C. All expected behavior.

The normal `swiper` will instead display the results in an additional minibuffer window D, not hiding A, B, or C. Which I think is superior.

**Comment by kgrimes2** [comment]
@abo-abo Ahh, I see. I wasn't aware that this was the expected behavior. Thanks!
