### ISSUE TITLE
Using visual-regexp-steroids.el

### ISSUE THREAD

**Issue by ghost** [abo-abo/swiper-helm#19]
I've been really enjoying swiper-helm so far. I'm also a huge fan of [visual-regexp-steroids.el](https://github.com/benma/visual-regexp-steroids.el/), which describes itself:

> visual-regexp-steroids is an extension to visual-regexp which enables the use of modern regexp engines (no more escaped group parentheses, and other goodies!). In addition to that, you can optionally use the better regexp syntax to power isearch-forward-regexp and isearch-backward-regexp.
>
> For now, Python and pcre2el is supported out of the box (tested on Linux and Windows). If you want to add custom scripts to enable your favorite language, please get in touch.

I also really like the live overview from swiper-helm, but I also really like using the Python-style regular expressions I'm wondering how pluggable swiper-helm is, and if it might be possible to adopt it toward using the visual-regexp-steroids regular expressions. I think a combination of these two would be my dream `C-s` binding.

Looking forward to your thoughts!

**Comment by abo-abo** [comment]
`swiper-helm` is mainly in maintenance mode, I keep it around because some people like it; I don't use it myself (I use swiper).

I'll usually just make fixes for when Helm breaks the API. I'll also accept PRs for feature requests such as this one.  I think you could hook up visual-regexp-steroids somewhere in the `match-strict` field of the `swiper-helm` function.

**Comment by ghost** [comment]
I appreciate your keeping these packages maintained! Thanks for the pointer to `match-strict`. I'll take a look there.
