### ISSUE TITLE
Difference with Helm Swoop. 

### ISSUE THREAD

**Issue by ReneFroger** [abo-abo/swiper-helm#5]
Thanks for sharing this package. However, I had a hard time to figure out what the differences of swiper-helm with ([Helm Swoop](https://github.com/ShingoFukuyama/helm-swoop/) are.

From what I noticed, Helm Swoop offers more features than Swiper, include the edit mode (`C-c C-e`). So I'm trying to figure out what the benefits of Swiper-Helm could be. Could you explain? Thanks!

**Comment by abo-abo** [comment]
This is just a clone of [swiper](https://github.com/abo-abo/swiper), a more powerful package.  I've used the `helm` API to prototype it, since `ivy-read` didn't exist at the time. Someone asked to keep this code around, since they really like `helm`, so it's here.

As for the `helm-swoop` comparison, `swiper-helm` has better coloring, more consistent regex builder, no annoying initial input, no annoying wrap-around.

As I mentioned above, `swiper` has all the features of `swiper-helm` and more:

- launch query-replace with <kbd>M-q</kbd>
- jump to a candidate on screen using `avy` on <kbd>C-'</kbd>
- own history
- a vi-like hydra on <kbd>C-o</kbd>
- customizable regex builder, matchers, formatters and more

**Comment by ReneFroger** [comment]
Thanks for your clear explaination. Notice that you could disable initial input in Helm Swoop. And how could you use the search history in swiper-helm? I noticed it in the demo video, but I couldn't figure out the keybindings to use it.

**Comment by abo-abo** [comment]
> Notice that you could disable initial input in Helm Swoop

That functionality wasn't available at the time, I think.

> And how could you use the search history in swiper-helm?

<kbd>M-n</kbd> and <kbd>M-p</kbd> should work.

**Comment by ReneFroger** [comment]
Clear enough! Thanks for your answers, it's appreciated!
